Introduction :

Let's first begin by building a dataframe of postal codes of each neighborhood along with the borough name and neighborhood name from wikipedia using beautifulSoup package. Then use Geocoder or csv file provided to get the latitude and the longitude coordinates of each neighborhood to utilize the Foursquare location data. Lastly we will explore and cluster the neighborhoods in Toronto based on the venue similarities/dissimilarities.

All Import Necessary Libraries

In [1]:
import requests
from bs4 import BeautifulSoup 
import pandas as pd 
import numpy as np 

from geopy.geocoders import Nominatim # Module to convert an address into latitude and longitude values
    
# Tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

import folium # Plotting library
from sklearn.cluster import KMeans # Import k-means from clustering stage

Building A Dataframe Of The Postal Code Of Each Neighborhood

Downloading And Scraping The Table from Wikipedia

In [2]:
url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"

# Get the contents of the webpage in text format and store in a variable called data
data  = requests.get(url).text

# Creating a beautifulSoup object
soup = BeautifulSoup(data,"html5lib")

# Create an empty table lists
table_contents=[]

# Finding tables from the wikipedia site
table=soup.find('table') # in html table is represented by the tag <table>

for row in table.findAll('td'):
    cell = {}
    if row.span.text=='Not assigned':
        pass
    else:
        cell['PostalCode'] = row.p.text[:3]
        cell['Borough'] = (row.span.text).split('(')[0]
        cell['Neighborhood'] = (((((row.span.text).split('(')[1]).strip(')')).replace(' /',',')).replace(')',' ')).strip(' ')
        table_contents.append(cell)
        
df=pd.DataFrame(table_contents)
df['Borough']=df['Borough'].replace({'Downtown TorontoStn A PO Boxes25 The Esplanade':'Downtown Toronto Stn A',
                                     'East TorontoBusiness reply mail Processing Centre969 Eastern':'East Toronto Business',
                                     'EtobicokeNorthwest':'Etobicoke Northwest','East YorkEast Toronto':'East York/East Toronto',
                                     'MississaugaCanada Post Gateway Processing Centre':'Mississauga'})

In [3]:
df.head()

  PostalCode           Borough                      Neighborhood
0        M3A        North York                         Parkwoods
1        M4A        North York                  Victoria Village
2        M5A  Downtown Toronto         Regent Park, Harbourfront
3        M6A        North York  Lawrence Manor, Lawrence Heights
4        M7A      Queen's Park     Ontario Provincial Government

In [4]:
df.shape

(103, 3)

In [5]:
df.tail()

,PostalCode,Borough,Neighborhood
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto Business,Enclave of M4L
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

Getting The Latitude And Longitude Coordinates Of Each Neighborhood

In [34]:
# Reading the latitude & longitude data from CSV file
# Create a dataframe of postalcodes and lat long coordinates
import io
import requests

url = "https://cocl.us/Geospatial_data"
lat_long = requests.get(url).text
lat_long_df=pd.read_csv(io.StringIO(lat_long))
lat_long_df.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [9]:
lat_long_df.rename(columns = {'Postal Code': 'PostalCode'}, inplace = True)

In [10]:
# Creating final dataframe with lot, long coordinates added onto the intial PostalCode dataframe

final_df_list = [] # Creating an empty list to store dictinories representing dataframe's rows and columns as keys
for i in range(df.shape[0]):
    Cell1 = {}
    PosCode = df.loc[i,'PostalCode']
    
    # Finding an index of the PostalCode in the df1 dataframe
    index = lat_long_df[lat_long_df['PostalCode']== PosCode].index.values[0]
    
    Cell1['PostalCode'] = PosCode
    Cell1['Borough'] = df.loc[i,'Borough']
    Cell1['Neighborhood'] = df.loc[i,'Neighborhood']
    
    # Assigning correct lat, long coordinates for the PostalCode to the df dataframe
    Cell1['Latitude'] = lat_long_df.loc[index,'Latitude']
    Cell1['Longitude'] = lat_long_df.loc[index,'Longitude']
    
    final_df_list.append(Cell1)
neighborhoods=pd.DataFrame(final_df_list)  # Creating final dataframe with lat, lon coordinates.

In [11]:
neighborhoods.head()

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Queen's Park,Ontario Provincial Government,43.662301,-79.389494

In [12]:
neighborhoods.tail()

,PostalCode,Borough,Neighborhood,Latitude,Longitude
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",43.653654,-79.506944
99,M4Y,Downtown Toronto,Church and Wellesley,43.665860,-79.383160
100,M7Y,East Toronto Business,Enclave of M4L,43.662744,-79.321558
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu...",43.636258,-79.498509
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,...",43.628841,-79.520999

In [35]:
neighborhoods.shape

(103, 5)

In [14]:
!conda install -c conda-forge folium=0.5.0 --yes

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Exploring The Neighborhoods in Toronto

In [15]:
address = 'Toronto'

geolocator = Nominatim(user_agent="ny_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geographical coordinate of Toronto are {}, {}.'.format(latitude, longitude))

The geographical coordinate of Toronto are 43.6534817, -79.3839347.

Create A Map Of Toronto With Neighborhoods Superimposed On Top

In [16]:
# Create map of neigborhoods using their PostalCodes' latitude and longitude values
map_toronto = folium.Map(location=[latitude, longitude], zoom_start=10)

# Add markers to map
for lat, lng, borough, neighborhood in zip(neighborhoods['Latitude'], neighborhoods['Longitude'], neighborhoods['Borough'], neighborhoods['Neighborhood']):
    label = '{}, ({})'.format(borough, neighborhood)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_toronto)  
map_toronto

Creating Dataframe Of Boroughs That Contains The Word Toronto

In [17]:
toronto_bor_list = [] # Intialize an empty list of boroughs that contains the word toronto

# Initialize the index to zero
i = 0
for bor in neighborhoods['Borough']:
    bor_list = bor.split(' ')
    cell_tor = {}  
    
    # Checking if the boroughs contains the word Toronto and append to a list
    if 'Toronto' in bor_list:
        cell_tor['Borough'] = neighborhoods.loc[i,'Borough']
        cell_tor['Neighborhood'] = neighborhoods.loc[i,'Neighborhood']
        cell_tor['Latitude'] = neighborhoods.loc[i,'Latitude']
        cell_tor['Longitude'] = neighborhoods.loc[i,'Longitude']
        toronto_bor_list.append(cell_tor)
    else:
        pass
    i+=1 # Increment the index by 1 
    
    
toronto_data = pd.DataFrame(toronto_bor_list)  # Creating dataframe of boroughs that contians the word Toronto.

In [18]:
# Create map of Toronto using latitude and longitude values
map_Toronto = folium.Map(location=[latitude, longitude], zoom_start=11)

# Add markers to map
for lat, lng, borough,neighborhood in zip(toronto_data['Latitude'], toronto_data['Longitude'],toronto_data['Borough'], toronto_data['Neighborhood']):
    label = '{}, ({})'.format(borough, neighborhood)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_Toronto)  
    
map_Toronto

Define Foursquare Credentials And Version

In [19]:
CLIENT_ID = 'DTI22PXVDGWZAZI3IDM3HHWJQYQLIJMDYGX3VJZ0NBRB0P3Q' # my Foursquare ID
CLIENT_SECRET = 'YA1UFSQW2FJLAKXQUO5DYFPEHAAIMGRLPTPGT0J4X2MBUIUX' # my Foursquare Secret
VERSION = '20180605' # Foursquare API version
LIMIT = 100 # A default Foursquare API limit value

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: DTI22PXVDGWZAZI3IDM3HHWJQYQLIJMDYGX3VJZ0NBRB0P3Q
CLIENT_SECRET:YA1UFSQW2FJLAKXQUO5DYFPEHAAIMGRLPTPGT0J4X2MBUIUX

Now, let's get the top 100 venues that are in Toronto's neighborhoods within a radius of 500 meters.

In [20]:
# Function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

Let's create a function to get the nearby venues that are in Toronto's neighborhoods

In [21]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # Create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # Make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # Return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

Creating the Toronto_venues dataframe using the above function on each neighborhood

In [22]:
toronto_venues = getNearbyVenues(names=toronto_data['Neighborhood'],
                                   latitudes=toronto_data['Latitude'],
                                   longitudes=toronto_data['Longitude']
                                  )

Regent Park, Harbourfront
Garden District, Ryerson
St. James Town
The Beaches
Berczy Park
Central Bay Street
Christie
Richmond, Adelaide, King
Dufferin, Dovercourt Village
The Danforth  East
Harbourfront East, Union Station, Toronto Islands
Little Portugal, Trinity
The Danforth West, Riverdale
Toronto Dominion Centre, Design Exchange
Brockton, Parkdale Village, Exhibition Place
India Bazaar, The Beaches West
Commerce Court, Victoria Hotel
Studio District
Lawrence Park
Roselawn
Davisville North
Forest Hill North & West
High Park, The Junction South
North Toronto West
The Annex, North Midtown, Yorkville
Parkdale, Roncesvalles
Davisville
University of Toronto, Harbord
Runnymede, Swansea
Moore Park, Summerhill East
Kensington Market, Chinatown, Grange Park
Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park
CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport
Rosedale
Enclave of M5E
St. James Town, Cabbagetown
First Canadian Place, Underground city
Church and Wellesley
Enclave of M4L

Checking the size of the resulting dataframe

In [23]:
toronto_venues.groupby('Neighborhood').count()

,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
Neighborhood,,,,,,
Berczy Park,58,58,58,58,58,58
"Brockton, Parkdale Village, Exhibition Place",24,24,24,24,24,24
"CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport",16,16,16,16,16,16
Central Bay Street,65,65,65,65,65,65
Christie,16,16,16,16,16,16
Church and Wellesley,79,79,79,79,79,79
"Commerce Court, Victoria Hotel",100,100,100,100,100,100
Davisville,37,37,37,37,37,37
Davisville North,7,7,7,7,7,7
"Dufferin, Dovercourt Village",14,14,14,14,14,14
Enclave of M4L,18,18,18,18,18,18
Enclave of M5E,99,99,99,99,99,99
"First Canadian Place, Underground city",100,100,100,100,100,100
Forest Hill North & West,4,4,4,4,4,4
"Garden District, Ryerson",100,100,100,100,100,100
"Harbourfront East, Union Station, Toronto Islands",100,100,100,100,100,100
"High Park, The Junction South",25,25,25,25,25,25
"India Bazaar, The Beaches West",23,23,23,23,23,23
"Kensington Market, Chinatown, Grange Park",66,66,66,66,66,66
Lawrence Park,3,3,3,3,3,3
"Little Portugal, Trinity",42,42,42,42,42,42
"Moore Park, Summerhill East",2,2,2,2,2,2
North Toronto West,20,20,20,20,20,20
"Parkdale, Roncesvalles",14,14,14,14,14,14
"Regent Park, Harbourfront",42,42,42,42,42,42
"Richmond, Adelaide, King",98,98,98,98,98,98
Rosedale,4,4,4,4,4,4
Roselawn,3,3,3,3,3,3
"Runnymede, Swansea",33,33,33,33,33,33
St. James Town,81,81,81,81,81,81
"St. James Town, Cabbagetown",43,43,43,43,43,43
Studio District,36,36,36,36,36,36
"Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park",13,13,13,13,13,13
"The Annex, North Midtown, Yorkville",21,21,21,21,21,21
The Beaches,4,4,4,4,4,4
The Danforth East,2,2,2,2,2,2
"The Danforth West, Riverdale",42,42,42,42,42,42
"Toronto Dominion Centre, Design Exchange",100,100,100,100,100,100
"University of Toronto, Harbord",33,33,33,33,33,33

Finding out how many unique categories can be curated from all the returned venues

In [24]:
print('There are {} uniques categories.'.format(len(toronto_venues['Venue Category'].unique())))

There are 231 uniques categories.

Analyze Each Neighborhood

In [25]:
# One hot encoding
toronto_onehot = pd.get_dummies(toronto_venues[['Venue Category']], prefix="", prefix_sep="")
toronto_onehot.rename(columns = {'Neighborhood': 'neighborhood'}, inplace = True)

# Add neighborhood column back to dataframe
toronto_onehot['Neighborhood'] = toronto_venues['Neighborhood']

# Move neighborhood column to the first column
fixed_columns = [toronto_onehot.columns[-1]] + list(toronto_onehot.columns[:-1])
toronto_onehot = toronto_onehot[fixed_columns]

toronto_onehot.head()

,Neighborhood,Adult Boutique,Airport,Airport Food Court,Airport Lounge,Airport Service,Airport Terminal,American Restaurant,Antique Shop,Aquarium,...,Theme Restaurant,Tibetan Restaurant,Toy / Game Store,Trail,Train Station,Vegetarian / Vegan Restaurant,Video Game Store,Vietnamese Restaurant,Wine Bar,Yoga Studio
0,"Regent Park, Harbourfront",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,"Regent Park, Harbourfront",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,"Regent Park, Harbourfront",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,"Regent Park, Harbourfront",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,"Regent Park, Harbourfront",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Grouping rows by neighborhood and by taking the mean of the frequency of occurrence of each category

In [26]:
toronto_grouped = toronto_onehot.groupby('Neighborhood').mean().reset_index()
toronto_grouped

,Neighborhood,Adult Boutique,Airport,Airport Food Court,Airport Lounge,Airport Service,Airport Terminal,American Restaurant,Antique Shop,Aquarium,...,Theme Restaurant,Tibetan Restaurant,Toy / Game Store,Trail,Train Station,Vegetarian / Vegan Restaurant,Video Game Store,Vietnamese Restaurant,Wine Bar,Yoga Studio
0,Berczy Park,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.017241,0.000000,0.000000,0.000000,0.000000
1,"Brockton, Parkdale Village, Exhibition Place",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
2,"CN Tower, King and Spadina, Railway Lands, Har...",0.000000,0.0625,0.0625,0.125,0.125,0.125,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
3,Central Bay Street,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.015385,0.000000,0.000000,0.015385,0.015385
4,Christie,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
5,Church and Wellesley,0.012658,0.0000,0.0000,0.000,0.000,0.000,0.012658,0.000000,0.00,...,0.012658,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.025316
6,"Commerce Court, Victoria Hotel",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.020000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.020000,0.000000,0.000000,0.010000,0.000000
7,Davisville,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.027027,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
8,Davisville North,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
9,"Dufferin, Dovercourt Village",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
10,Enclave of M4L,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.055556
11,Enclave of M5E,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.010101,0.010101,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.010101,0.000000,0.000000,0.000000,0.010101
12,"First Canadian Place, Underground city",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.020000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.01,0.010000,0.000000,0.000000,0.010000,0.000000
13,Forest Hill North & West,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.25000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
14,"Garden District, Ryerson",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.010000,0.010000,0.010000,0.000000
15,"Harbourfront East, Union Station, Toronto Islands",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.03,...,0.000000,0.00000,0.000000,0.00000,0.01,0.000000,0.000000,0.000000,0.010000,0.000000
16,"High Park, The Junction South",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.040000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
17,"India Bazaar, The Beaches West",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
18,"Kensington Market, Chinatown, Grange Park",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.045455,0.000000,0.045455,0.015152,0.000000
19,Lawrence Park,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
20,"Little Portugal, Trinity",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.047619,0.000000,0.047619,0.023810,0.023810
21,"Moore Park, Summerhill East",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
22,North Toronto West,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.050000
23,"Parkdale, Roncesvalles",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
24,"Regent Park, Harbourfront",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.023810,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.023810
25,"Richmond, Adelaide, King",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.020408,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.010204,0.000000,0.000000,0.000000,0.000000
26,Rosedale,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.25000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
27,Roselawn,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
28,"Runnymede, Swansea",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.030303,0.000000,0.000000,0.000000,0.030303
29,St. James Town,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.024691,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.012346,0.000000,0.000000,0.012346,0.000000
30,"St. James Town, Cabbagetown",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.023256,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
31,Studio District,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.055556,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.027778
32,"Summerhill West, Rathnelly, South Hill, Forest...",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.076923,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.076923,0.000000,0.000000
33,"The Annex, North Midtown, Yorkville",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
34,The Beaches,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.25000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
35,The Danforth East,0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000
36,"The Danforth West, Riverdale",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.023810,0.000000,0.00,...,0.000000,0.02381,0.000000,0.02381,0.00,0.000000,0.000000,0.000000,0.000000,0.023810
37,"Toronto Dominion Centre, Design Exchange",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.020000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.01,0.010000,0.000000,0.000000,0.010000,0.000000
38,"University of Toronto, Harbord",0.000000,0.0000,0.0000,0.000,0.000,0.000,0.000000,0.000000,0.00,...,0.000000,0.00000,0.000000,0.00000,0.00,0.000000,0.030303,0.000000,0.000000,0.030303

Confirming the new size

In [27]:
toronto_grouped.shape

(39, 232)

Printing each neighborhood along with the top 5 most common venues

In [28]:
num_top_venues = 5

for hood in toronto_grouped['Neighborhood']:
    print("----"+hood+"----")
    temp = toronto_grouped[toronto_grouped['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Berczy Park----
          venue  freq
0   Coffee Shop  0.10
1  Cocktail Bar  0.05
2        Bakery  0.05
3   Cheese Shop  0.03
4      Beer Bar  0.03


----Brockton, Parkdale Village, Exhibition Place----
            venue  freq
0            Café  0.12
1  Breakfast Spot  0.08
2          Bakery  0.08
3     Coffee Shop  0.08
4       Pet Store  0.04


----CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport----
              venue  freq
0    Airport Lounge  0.12
1   Airport Service  0.12
2  Airport Terminal  0.12
3          Boutique  0.06
4           Airport  0.06


----Central Bay Street----
                 venue  freq
0          Coffee Shop  0.17
1                 Café  0.05
2       Sandwich Place  0.05
3   Italian Restaurant  0.05
4  Japanese Restaurant  0.03


----Christie----
           venue  freq
0  Grocery Store  0.25
1           Café  0.19
2           Park  0.12
3     Baby Store  0.06
4      Nightclub  0.06


----Church and Wellesley----
                 venue  freq
0          Coffee Shop  0.08
1     Sushi Restaurant  0.06
2  Japanese Restaurant  0.06
3           Restaurant  0.04
4              Gay Bar  0.04


----Commerce Court, Victoria Hotel----
          venue  freq
0   Coffee Shop  0.14
1         Hotel  0.06
2          Café  0.06
3    Restaurant  0.05
4  Cocktail Bar  0.04


----Davisville----
            venue  freq
0     Pizza Place  0.11
1  Sandwich Place  0.08
2    Dessert Shop  0.08
3            Café  0.05
4     Coffee Shop  0.05


----Davisville North----
               venue  freq
0               Park  0.14
1   Department Store  0.14
2     Breakfast Spot  0.14
3        Pizza Place  0.14
4  Food & Drink Shop  0.14


----Dufferin, Dovercourt Village----
         venue  freq
0     Pharmacy  0.14
1       Bakery  0.14
2    Pet Store  0.07
3  Music Venue  0.07
4         Café  0.07


----Enclave of M4L----
                venue  freq
0  Light Rail Station  0.11
1         Yoga Studio  0.06
2       Auto Workshop  0.06
3          Skate Park  0.06
4       Burrito Place  0.06


----Enclave of M5E----
                venue  freq
0         Coffee Shop  0.12
1  Italian Restaurant  0.04
2  Seafood Restaurant  0.04
3                Café  0.03
4               Hotel  0.03


----First Canadian Place, Underground city----
           venue  freq
0    Coffee Shop  0.10
1           Café  0.07
2            Gym  0.05
3          Hotel  0.05
4  Deli / Bodega  0.04


----Forest Hill North & West----
              venue  freq
0              Park  0.25
1             Trail  0.25
2     Jewelry Store  0.25
3  Sushi Restaurant  0.25
4    Adult Boutique  0.00


----Garden District, Ryerson----
            venue  freq
0     Coffee Shop  0.10
1  Clothing Store  0.07
2            Café  0.04
3  Sandwich Place  0.04
4           Hotel  0.04


----Harbourfront East, Union Station, Toronto Islands----
            venue  freq
0     Coffee Shop  0.19
1            Café  0.05
2        Aquarium  0.03
3  Scenic Lookout  0.03
4      Restaurant  0.03


----High Park, The Junction South----
                venue  freq
0                Café  0.08
1  Mexican Restaurant  0.08
2     Thai Restaurant  0.08
3                Park  0.04
4           Gastropub  0.04


----India Bazaar, The Beaches West----
                  venue  freq
0                  Park  0.13
1  Fast Food Restaurant  0.09
2     Food & Drink Shop  0.04
3                   Pub  0.04
4               Brewery  0.04


----Kensington Market, Chinatown, Grange Park----
                           venue  freq
0                           Café  0.08
1  Vegetarian / Vegan Restaurant  0.05
2                            Bar  0.05
3                         Bakery  0.05
4                    Coffee Shop  0.05


----Lawrence Park----
            venue  freq
0            Park  0.33
1        Bus Line  0.33
2     Swim School  0.33
3  Lingerie Store  0.00
4          Lounge  0.00


----Little Portugal, Trinity----
                           venue  freq
0                            Bar  0.10
1                     Restaurant  0.05
2          Vietnamese Restaurant  0.05
3  Vegetarian / Vegan Restaurant  0.05
4                           Café  0.05


----Moore Park, Summerhill East----
                 venue  freq
0               Lawyer   0.5
1           Playground   0.5
2       Adult Boutique   0.0
3  Monument / Landmark   0.0
4     Malay Restaurant   0.0


----North Toronto West----
            venue  freq
0     Coffee Shop  0.10
1  Clothing Store  0.10
2     Yoga Studio  0.05
3      Bagel Shop  0.05
4  Cosmetics Shop  0.05


----Parkdale, Roncesvalles----
            venue  freq
0  Breakfast Spot  0.14
1       Gift Shop  0.14
2     Coffee Shop  0.07
3             Bar  0.07
4   Movie Theater  0.07


----Regent Park, Harbourfront----
         venue  freq
0  Coffee Shop  0.19
1          Pub  0.07
2         Park  0.07
3       Bakery  0.07
4         Café  0.05


----Richmond, Adelaide, King----
             venue  freq
0      Coffee Shop  0.10
1             Café  0.05
2  Thai Restaurant  0.04
3       Restaurant  0.04
4    Deli / Bodega  0.03


----Rosedale----
                             venue  freq
0                             Park  0.50
1                       Playground  0.25
2                            Trail  0.25
3  Molecular Gastronomy Restaurant  0.00
4                     Liquor Store  0.00


----Roselawn----
            venue  freq
0          Garden  0.33
1    Home Service  0.33
2     Music Venue  0.33
3  Adult Boutique  0.00
4          Lounge  0.00


----Runnymede, Swansea----
                venue  freq
0                Café  0.09
1         Coffee Shop  0.09
2    Sushi Restaurant  0.06
3                 Pub  0.06
4  Italian Restaurant  0.06


----St. James Town----
          venue  freq
0   Coffee Shop  0.06
1          Café  0.05
2      Beer Bar  0.04
3  Cocktail Bar  0.04
4     Gastropub  0.04


----St. James Town, Cabbagetown----
         venue  freq
0  Coffee Shop  0.07
1       Bakery  0.07
2         Café  0.05
3  Pizza Place  0.05
4          Pub  0.05


----Studio District----
                 venue  freq
0          Coffee Shop  0.08
1              Brewery  0.06
2               Bakery  0.06
3            Gastropub  0.06
4  American Restaurant  0.06


----Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park----
                 venue  freq
0          Coffee Shop  0.15
1          Pizza Place  0.08
2   Light Rail Station  0.08
3  Fried Chicken Joint  0.08
4           Restaurant  0.08


----The Annex, North Midtown, Yorkville----
            venue  freq
0     Coffee Shop  0.14
1            Café  0.14
2  Sandwich Place  0.14
3     Pizza Place  0.05
4       BBQ Joint  0.05


----The Beaches----
               venue  freq
0       neighborhood  0.25
1  Health Food Store  0.25
2                Pub  0.25
3              Trail  0.25
4     Adult Boutique  0.00


----The Danforth  East----
                 venue  freq
0                 Park   0.5
1    Convenience Store   0.5
2  Monument / Landmark   0.0
3               Lounge   0.0
4     Malay Restaurant   0.0


----The Danforth West, Riverdale----
                    venue  freq
0        Greek Restaurant  0.17
1             Coffee Shop  0.10
2      Italian Restaurant  0.07
3  Furniture / Home Store  0.05
4              Restaurant  0.05


----Toronto Dominion Centre, Design Exchange----
                venue  freq
0         Coffee Shop  0.11
1               Hotel  0.08
2                Café  0.06
3  Seafood Restaurant  0.03
4         Salad Place  0.03


----University of Toronto, Harbord----
                 venue  freq
0                 Café  0.15
1                  Bar  0.06
2  Japanese Restaurant  0.06
3            Bookstore  0.06
4               Bakery  0.06

Let's put that into a pandas dataframe

In [29]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [30]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# Create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# Create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = toronto_grouped['Neighborhood']

for ind in np.arange(toronto_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(toronto_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Berczy Park,Coffee Shop,Cocktail Bar,Bakery,Cheese Shop,Beer Bar,Restaurant,Farmers Market,Seafood Restaurant,Café,Bistro
1,"Brockton, Parkdale Village, Exhibition Place",Café,Breakfast Spot,Bakery,Coffee Shop,Furniture / Home Store,Burrito Place,Restaurant,Italian Restaurant,Intersection,Bar
2,"CN Tower, King and Spadina, Railway Lands, Har...",Airport Lounge,Airport Service,Airport Terminal,Harbor / Marina,Bar,Coffee Shop,Boat or Ferry,Boutique,Rental Car Location,Plane
3,Central Bay Street,Coffee Shop,Sandwich Place,Italian Restaurant,Café,Salad Place,Restaurant,Bubble Tea Shop,Japanese Restaurant,Burger Joint,Yoga Studio
4,Christie,Grocery Store,Café,Park,Italian Restaurant,Baby Store,Athletics & Sports,Restaurant,Candy Store,Coffee Shop,Nightclub

Cluster Neighborhoods

Run k-means to cluster the neighborhood into 5 clusters.

In [31]:
# Set number of clusters
kclusters = 5

toronto_grouped_clustering = toronto_grouped.drop('Neighborhood', 1)

# Run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(toronto_grouped_clustering)

# Check cluster labels generated for each row in the dataframe
kmeans.labels_[0:15]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3], dtype=int32)

In [39]:
# Add clustering labels to the dataframe with the top 10 venues for each neigborhood
neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

toronto_merged = toronto_data

# Merge manhattan_grouped with manhattan_data to add latitude/longitude for each neighborhood
toronto_merged = toronto_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood')

toronto_merged.head()

ValueError: cannot insert Cluster Labels, already exists

In [38]:
# Create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# Set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# Add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged['Latitude'], toronto_merged['Longitude'], toronto_merged['Neighborhood'], toronto_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters